- hosts: all
#  become: true
  vars:
    create_containers: 1
    default_container_name: santuapp
    default_container_image: santuapp4:0

  tasks:
    - name: copy Dockerfile
      copy:
        src: /var/lib/jenkins/workspace/santu_project/arttifact-jfrog/Dockerfile
        dest: /opt/apps/tomcat/Dockerfile
        

    - name: Copy war file
      copy:
        src: /var/lib/jenkins/workspace/santu_project/arttifact-jfrog/target/dockeransible.war
        dest: /opt/apps/tomcat/
        
        
    - name: build container image
      docker_image:
        name: "{{ default_container_image }}"
        build:
           path: /opt/apps/tomcat/
           
       
    - name: push container image
      docker_image:
        name: "{{ default_container_image }}"
        repository: santudev.jfrog.io/santuapp/santuapp4:0
        push: yes
