- hosts: all
#  become: true
  vars:
    create_containers: 1
    default_container_name: santuapp
    default_container_image: santu459/santuapp:2.0

  tasks:
    - name: copy Dockerfile
      copy:
        src: /var/lib/jenkins/workspace/santu_project/arttifact-jfrog/Dockerfile
        dest: /opt/apps/tomcat/Dockerfile
		remote_src: yes
    - name: Install docker-py python module
      copy:
        src: /var/lib/jenkins/workspace/santu_project/arttifact-jfrog/target/*.war
        dest: /opt/apps/tomcat/
		remote_src: yes
    - name: build container image
      docker_image:
        name: "{{ default_container_image }}"
		build:
			path: /opt/apps/tomcat/Dockerfile
			source: build
		state: present
		
    - name: push container image
      docker_image:
        name: "{{ default_container_image }}"
		repository: santu459/santuapp:2.0
		push: yes
